resource "local_file" "main" {
  filename = "QA/file1.txt"
  content  = "This is file number 1 <increment here> for QA env generated by terraform, The user inputed text is : < DO NOT HARDCODE, this TEXT can be anything, different for each file and env>"
}