resource "local_file" "main" {
  count    = length(local.files)
  filename = local.files[count.index].path

  content = "This is file number ${local.files[count.index].idx} for ${local.files[count.index].folder} env generated by terraform, The user inputed text is : ${var.user_text[local.files[count.index].folder]}\n"
}